
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LibraryManagement
{

using System;
    using System.Collections.Generic;
    
public partial class BOOK
{

    public int BOOK_ID { get; set; }

    public string BOOK_NAME { get; set; }

    public string CATEGORY { get; set; }

    public string AUTHOR { get; set; }

    public string STATUS { get; set; }

    public string CREATED_BY { get; set; }

    public Nullable<System.DateTime> CREATE_TIMESTAMP { get; set; }

    public string UPDATED_BY { get; set; }

    public Nullable<System.DateTime> UPDATE_TIMESTAMP { get; set; }



    public virtual CATEGORY CATEGORY1 { get; set; }

}

}
